name: Build Docker Images for all microservices and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api-gateway
        run: |
          docker build -f ./api-gateway/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build and push menu-service
        run: |
          docker build -f ./menu-services/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/menu-service:latest ./menu-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/menu-service:latest

      - name: Build and push order-service
        run: |
          docker build -f ./order-services/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest ./order-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

      - name: Build and push payment-service
        run: |
          docker build -f ./payment-services/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest ./payment-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest

      - name: Build and push inventory-service
        run: |
          docker build -f ./inventory-services/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest ./inventory-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest

      - name: Build and push customer-service
        run: |
          docker build -f ./customer-services/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest ./customer-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest

      